let
    Source = Excel.Workbook(File.Contents("C:\Users\ANANYA\OneDrive\Documents\dataset_raw.xlsx"), null, true),
    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"City", type text}, {"State", type text}, {"Country", type text}, {"Postal Code", Int64.Type}, {"Market", type text}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}, {"Shipping Cost", type number}, {"Order Priority", type text}}),
    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type", {"Order Priority", "Shipping Cost", "Profit", "Discount", "Quantity", "Sales", "Product Name", "Sub-Category", "Category", "Product ID", "Region", "Market", "Postal Code", "Country", "State", "City", "Segment", "Customer Name", "Customer ID", "Ship Mode", "Ship Date", "Order Date", "Order ID", "Row ID"}),
    #"Replaced Errors" = Table.ReplaceErrorValues(#"Removed Errors", {{"Row ID", 0}}),
    #"Replaced Errors1" = Table.ReplaceErrorValues(#"Replaced Errors", {{"Order ID", "NULL"}}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Replaced Errors1", "Order ID", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"Order ID.1", "Order ID.2", "Order ID.3"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Order ID.1", type text}, {"Order ID.2", Int64.Type}, {"Order ID.3", Int64.Type}}),
    #"Added Conditional Column" = Table.AddColumn(#"Changed Type1", "Profitability", each if [Profit] > 0 then "Profitable" else "Loss")
in
    #"Added Conditional Column"